ecom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core.views import (
    HomeView,
    ContactView,
    ProfileView
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('store/', include('store.urls', namespace='store')),
    path('accounts/', include('allauth.urls')),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('staff/', include('staff.urls', namespace='staff')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product-list'),
    path('cart/', views.CatView.as_view(), name='cart'),
    path('checkout/', views.CheckoutView .as_view(), name='checkout'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('thank-you/', views.ThankYouView.as_view(), name='thank-you'),
    path('confirm-order/', views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('orders/<pk>/', views.OrderDetailView.as_view(), name='order-detail'),
    path('<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('increase-quantity/<pk>/', views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>/', views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('delete-orderitem/<pk>/', views.DeleteOrderItemView.as_view(), name='delete-order-item'),
]

store/forms.py
from django.contrib.auth import get_user_model
from django import forms
from .models import (
    OrderItem, ColorVariation, 
    SizeVariation, Product, Address )

User = get_user_model() 

class AddToCartForm(forms.ModelForm):
    colors = forms.ModelChoiceField(queryset=ColorVariation.objects.none())
    size = forms.ModelChoiceField(queryset=SizeVariation.objects.none())
    quantity = forms.IntegerField(max_value=1)
    class Meta:
        model = OrderItem
        fields = ['quantity', 'colors', 'size']

    def __init__(self, *args, **kwargs):
        self.product_id = kwargs.pop('product_id')
        product = Product.objects.get(id=self.product_id)
        super().__init__(*args, **kwargs)

        self.fields['colors'].queryset = product.available_colors.all()
        self.fields['size'].queryset = product.available_sizes.all()

    def clean(self):
        product_id = self.product_id
        product = Product.objects.get(id=self.product_id)
        quantity = self.cleaned_data['quantity']

        if product.stock < quantity:
            raise forms.ValidationError(f"The maximum stock available is {product.stock}")

class AddressForm(forms.Form):
    
    shipping_address_line_1 = forms.CharField(required=False)
    shipping_address_line_2 = forms.CharField(required=False)
    shipping_zip_code = forms.CharField(required=False)
    shipping_city = forms.CharField(required=False)

    billing_address_line_1 = forms.CharField(required=False)
    billing_address_line_2 = forms.CharField(required=False)
    billing_zip_code = forms.CharField(required=False)
    billing_city = forms.CharField(required=False)

    selected_shipping_address = forms.ModelChoiceField(
        Address.objects.none(), required=False
    )

    selected_billing_address = forms.ModelChoiceField(
        Address.objects.none(), required=False
    )

    def __init__(self, *args, **kwargs):
        user_id = kwargs.pop('user_id')
        super().__init__(*args, **kwargs)
        if user_id is not None:
            user = User.objects.get(id=user_id)

            shipping_address_qs = Address.objects.filter(
                user=user,
                address_type='S'
            )
            billing_address_qs = Address.objects.filter(
                user=user,
                address_type='B'
            )
            self.fields['selected_shipping_address'].queryset = shipping_address_qs
            self.fields['selected_billing_address'].queryset = billing_address_qs

    def clean(self):
        data = self.cleaned_data

        selected_shipping_address = data.get('selected_shipping_address', None)
        if selected_shipping_address is None:
            if not data.get('shipping_address_line_1', None):
                self.add_error("shipping_address_line_1", "Please fill in this field")
            if not data.get('shipping_address_line_2', None):
                self.add_error("shipping_address_line_2", "Please fill in this field")
            if not data.get('shipping_zip_code', None):
                self.add_error("shipping_zip_code", "Please fill in this field")
            if not data.get('shipping_city', None):
                self.add_error("shipping_city", "Please fill in this field")

        selected_billing_address = data.get('selected_billing_address', None)
        if selected_billing_address is None:
            if not data.get('billing_address_line_1', None):
                self.add_error("billing_address_line_1", "Please fill in this field")
            if not data.get('billing_address_line_2', None):
                self.add_error("billing_address_line_2", "Please fill in this field")
            if not data.get('billing_zip_code', None):
                self.add_error("billing_zip_code", "Please fill in this field")
            if not data.get('billing_city', None):
                self.add_error("billing_city", "Please fill in this field")

store/views.py
import datetime
import json
from django.conf import settings
from django.contrib import messages
from django.views import generic
from django.db.models import Q
from django.http import JsonResponse
from .models import Product, OrderItem, Address, Payment, Order, Category
from django.shortcuts import get_object_or_404, reverse, redirect
from .utils import get_or_set_order_session
from .forms import AddToCartForm, AddressForm
from django.contrib.auth.mixins import LoginRequiredMixin


class ProductListView(generic.ListView):
    template_name = 'store/product_list.html'
    

    def get_queryset(self):
        qs = Product.objects.all()
        category = self.request.GET.get('category', None)

        if category:
            qs = qs.filter(Q(primary_category__name=category) | 
                        Q(secondary_categories__name=category)).distinct()
        return qs

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context.update({
            'categories': Category.objects.all()
        })
        return context

class ProductDetailView(generic.FormView):
    template_name = 'store/product_detail.html'
    form_class = AddToCartForm

    def get_object(self):
        return get_object_or_404(Product, slug=self.kwargs['slug'])

    def get_success_url(self):
        return reverse('store:cart') # Reverse to Cart

    def get_form_kwargs(self):
        kwargs = super(ProductDetailView, self).get_form_kwargs()
        kwargs['product_id'] = self.get_object().id
        return kwargs

    def form_valid(self, form):
        order = get_or_set_order_session(self.request)
        product = self.get_object()

        item_filter = order.items.filter(
            product=product, 
            colors=form.cleaned_data['colors'],
            size=form.cleaned_data['size']
        )

        if item_filter.exists():
            item = item_filter.first()
            item.quantity += int(form.cleaned_data['quantity'])
            item.save()

        else:
            new_item = form.save(commit=False)
            new_item.product = product 
            new_item.order = order
            new_item.save()
        return super(ProductDetailView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['product'] = self.get_object()
        return context

class CatView(generic.TemplateView):
    template_name = 'store/cart.html'
    
    def get_context_data(self, **kwargs):
        context = super(CatView, self).get_context_data(**kwargs)
        context['order'] = get_or_set_order_session(self.request)
        return context

class IncreaseQuantityView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.quantity += 1
        order_item.save()
        return redirect('store:cart')


class DecreaseQuantityView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        if order_item.quantity <= 1:
            order_item.delete()
        else:
            order_item.quantity -= 1
            order_item.save()
        return redirect('store:cart')

class DeleteOrderItemView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.delete()
        return redirect('store:cart')

class CheckoutView(generic.FormView):
    template_name = 'store/checkout.html'
    form_class = AddressForm


    def get_success_url(self):
        return reverse('store:payment') 

    def form_valid(self, form):
        order = get_or_set_order_session(self.request)

        selected_shipping_address = form.cleaned_data.get('selected_shipping_address')
        selected_billing_address = form.cleaned_data.get('selected_billing_address')

        if selected_shipping_address:
            order.shipping_address = selected_shipping_address
        else:
            address = Address.objects.create(
                address_type='S',
                user=self.request.user,
                address_line_1=form.cleaned_data["shipping_address_line_1"],
                address_line_2=form.cleaned_data["shipping_address_line_2"],
                zip_code=form.cleaned_data["shipping_zip_code"],
                city=form.cleaned_data["shipping_city"],
            )
            order.shipping_address = address
           

        if selected_billing_address:
            order.billing_address = selected_billing_address
        else:
            address = Address.objects.create(
                address_type='B',
                user=self.request.user,
                address_line_1=form.cleaned_data["billing_address_line_1"],
                address_line_2=form.cleaned_data["billing_address_line_2"],
                zip_code=form.cleaned_data["billing_zip_code"],
                city=form.cleaned_data["billing_city"],
            )
            order.billing_address = address
            order.save()

        messages.info(
            self.request, "You have successfully added your addresses"
        )
        return super(CheckoutView, self).form_valid(form)


    def get_form_kwargs(self):
        kwargs = super(CheckoutView, self).get_form_kwargs()
        kwargs['user_id'] = self.request.user.id
        return kwargs
    
    def get_context_data(self, **kwargs):
        context = super(CheckoutView, self).get_context_data(**kwargs)
        context['order'] = get_or_set_order_session(self.request)
        return context

class PaymentView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'store/payment.html'

    def get_context_data(self, **kwargs):
        context = super(PaymentView, self).get_context_data(**kwargs)
        context['PAYPAL_CLIENT_ID'] = settings.PAYPAL_CLIENT_ID
        context['order'] = get_or_set_order_session(self.request)
        context['CALLBACK_URL'] = self.request.build_absolute_uri(reverse("store:thank-you"))
        return context 

class ConfirmOrderView(generic.View):
    def post(self, request, *args, **kwargs):
        order = get_or_set_order_session(request)
        body = json.loads(request.body)
        payment = Payment.objects.create(
            order=order,
            successful=True,
            raw_response=json.dumps(body),
            amount=float(body["purchase_units"][0]["amount"]["value"]),
            payment_method='Paypal',
        )
        order.ordered = True
        order.ordered_date = datetime.date.today()
        order.save()
        return JsonResponse({"data": "Success"})

class ThankYouView(generic.TemplateView):
    template_name = 'store/thanks.html' 

class OrderDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'order.html'
    queryset = Order.objects.all()
    context_object_name = 'order'

templates/store/cart.html
{% extends 'base.html' %}

{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'store:product-list' %}">Store</a>
                <span class="mx-2 mb-0"> > </span>
                <strong class="text-black">Cart</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-12">
                <div class="site-blocks-table">
                    <table>
                        <thead>
                        <tr>
                            <th>Image</th>
                            <th>Product</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Total</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for item in order.items.all %}
                            <tr>
                                <td class="product-thumbnail">
                                    <img src="{{ item.product.image.url }}" alt="" class="img-fluid">
                                </td>
                                <td>
                                <div class="product-name">
                                    <h2 class="h5 text-black"> {{ item.product.title }}</h2>
                                    <small>Size: {{ item.size.name }}</small>
                                    <small>Color: {{ item.colors.name }}</small>
                                </div>
                                </td>
                                <td>$ {{ item.product.get_price }}</td>
                                <td>
                                    <div class="input-group mb-3" style="max-width: 120px;">
                                        <div class="input-group-prepend">
                                            <a href="{% url 'store:decrease-quantity' item.id %}" class="btn btn-outline-primary">
                                                &minus;
                                            </a>
                                        </div>
                                        <input type="text" class="form-control text-center" value="{{ item.quantity }}">
                                        <div class="input-group-append">
                                            <a href="{% url 'store:increase-quantity' item.id %}" class="btn btn-outline-primary">
                                                &plus;
                                            </a>
                                        </div>
                                    </div>
                                </td>
                                 <td>
                                 ${{ item.get_total_item_price }}
                                 </td>
                                 <td>
                                    <a href="{% url 'store:delete-order-item' item.id %}" class="btn btn-primary btn-sm">X</a>
                                 </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan="6">
                                    There are no items in your cart.
                                    <a href="{% url 'store:product-list' %}">Continue shopping</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                
            </div>    
        </div>

        {% if order.items.count > 0 %}
            <div class="row">
                <div class="col-md-6">
                    <div class="row mb-5">
                        <div class="col-md-12">
                            <a class="btn btn-outline-primary btn-sm btn-block"
                             href="{% url 'store:product-list' %}">Continue shoping</a>
                        </div>
                    </div>
                </div>

                <div class="col-md-6 pl-5">
                <div class="row justify-content-end">
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-12 text-right border-bottom mb-5">
                                <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <span class="text-black">Subtotal</span>
                            </div>
                            <div class="col-md-6 text-right">
                                <strong class="text-black">${{ order.get_subtotal }}</strong>
                            </div>
                        </div>
                        <div class="row mb-5">
                            <div class="col-md-6">
                                <span class="text-black">Total</span>
                            </div>
                            <div class="col-md-6 text-right">
                                <strong class="text-black">${{ order.get_total }}</strong>
                            </div>
                        </div>
                         <div class="row">
                            <div class="col-md-12">
                                <a class="btn btn-primary btn-lg py-3 btn-block" href="{% url 'store:checkout' %}">Proceed to checkout</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>            
        {% endif %}
    </div>
</div>

{% endblock content %}

templates/store/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'store:product-list' %}">Store</a>
                <span class="mx-2 mb-0"> > </span>
                <a href="{% url 'store:cart' %}">Cart</a>
                <span class="mx-2 mb-0"> > </span>
                <strong class="text-black">Checkout</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">    
        {% if not request.user.is_authenticated %}
        <div class="row mb-5">
            <div class="col-md-12">
                <div class="border p-4 rounded" role="alert">
                    You are nearly finished with your order.
                    To finalize your order, please <a href="{% url 'account_login' %}">Login</a> or <a href="{% url 'account_signup' %}">Signup</a>
                </div>
                <div class="progress">
                    <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: 90%" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100">90% Complete</div>
                </div>
            </div>
        </div>
        {% else %}
        <form action="" method='post'>
        {% csrf_token %}
         <div class="row">
            <div class="col-md-6 mb-5 mb-md-0">
                <h2 class="h3 mb-3 text-black text-center">Billing Details</h2>
                <hr>
                <div class="p-2 p-lg-2">
                    {{ form|crispy}}
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-lg py-3 btn-block">
                    Proceed to payment
                    </button>
                </div>
            </div>
            <div class="col-md-6">
                 <div class="row mb-5">
                        <div class="col-md-12">
                           <h2 class="h3 mb-3 text-black text-center">Your Order</h2>
                           <hr>
                           <div class="p-3 py-lg-5">
                    <table class="table site-block-order-table mb-5">
                        <thead>
                            <th>Product</th>
                            <th>Total</th>
                        </thead>
                        <tbody>
                            {% for item in order.items.all %}
                            <tr>
                                <td>
                                  {{ item.size.name}}, {{ item.colors.name}} {{ item.product.title}}
                                  <strong class="mx-2">x</strong> {{ item.quantity }}
                                </td>
                                 <td>
                                 ${{ item.get_total_item_price }}
                                 </td>
                            </tr>
                            {% endfor %}
                            <tr>
                                <td><strong>Subtotal</strong></td>
                                <td>${{order.get_subtotal }}</td>
                            </tr>
                            <tr>
                                <td><strong class="text-black font-weight-bold">Order Total</strong></td>
                                <td><strong class="text-black font-weight-bold">${{order.get_total }}</strong></td>
                            </tr>
                        </tbody>
                    </table>
                           </div>
                        </div>
                    </div>
            </div>
         </div>
        </form>
        {% endif %}   
    </div>
</div>

{% endblock content %}

templates/store/payment.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
  @keyframes ldio-ogchend7tu8 {
    0% {
      transform: translate(-50%, -50%) rotate(0deg);
    }

    100% {
      transform: translate(-50%, -50%) rotate(360deg);
    }
  }

  .ldio-ogchend7tu8 div {
    position: absolute;
    width: 120px;
    height: 120px;
    border: 20px solid #93dbe9;
    border-top-color: transparent;
    border-radius: 50%;
  }

  .ldio-ogchend7tu8 div {
    animation: ldio-ogchend7tu8 1s linear infinite;
    top: 100px;
    left: 100px
  }

  .loadingio-spinner-rolling-9nfnnlwpxp4 {
    width: 200px;
    height: 200px;
    display: inline-block;
    overflow: hidden;
    background: #f1f2f3;
  }

  .ldio-ogchend7tu8 {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0;
    /* see note above */
  }

  .ldio-ogchend7tu8 div {
    box-sizing: content-box;
  }

  /* generated by https://loading.io/ */
</style>

<div class="container">
    <div class="row justify-content-center h-100">
    <div class="col-md-6 h-100">
    <div class="alert alert-success" role="alert" id="alertSuccess" style="display: none;">
      Your payment was successful
    </div>
    <div class="alert alert-danger" role="alert" id="alertFailure" style="display: none;">
      Your payment failed. Please try again.
    </div>
    <div class="text-center py-3">
      <divclass="loadingio-spinner-rolling-9nfnnlwpxp4">
        <div id="loader" style="margin: auto; display: none;" class="ldio-ogchend7tu8">
          <div></div>
        </div>
      </divclass=>
    </div>
      <div id="paymentInfo">
        <p>Order total: ${{ order.get_total }}</p>
        <h4>Select a payment method</h4>
        <div id="paypal-button-container" class="h-100"></div>
      </div>
    </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}

<script src="https://www.paypal.com/sdk/js?client-id={{PAYPAL_CLIENT_ID }}"></script>
<script>

  const loader = document.getElementById('loader');
  const paymentInfo = document.getElementById('paymentInfo');

  function toggleLoader(on) {
    loader.style.display = on === true ? "block" : "none";
    paymentInfo.style.display = on === true ? "none" : "block";
  }

  function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
const csrftoken = getCookie('csrftoken');

  function sendOrderConfirmed(details) {
    return fetch("{% url 'store:confirm-order' %}", {
      method: "post",
      body: JSON.stringify(details),
      headers: {
        "Content-type": "application/json",
        "X-CSRFToken": csrftoken
      }
    })
  }

  paypal.Buttons({
    createOrder: function(data, actions) {
      // This function sets up the details of the transaction, including the amount and line item details.
      return actions.order.create({
        purchase_units: [{
          amount: {
            value: '{{order.get_total}}'
          }
        }]
      });
    },
    onApprove: function(data, actions) {
      toggleLoader(true);
      // This function captures the funds from the transaction.
      return actions.order.capture().then(function(details) {
        // This function shows a transaction success message to your buyer.
          sendOrderConfirmed(details).then(res => {
            toggleLoader(false)
            const alertSuccess = document.getElementById('alertSuccess');
            alertSuccess.style.display = 'block';
            setTimeout(function() {
              window.location.replace("{{ CALLBACK_URL }}")
            }, 3000);
        })
      })
      .catch(err => {
        const alertFailure = documement.getElementById('alertFailure');
        alertFailure.style.display = 'block';
      })
      .finally(() => toggleLoader(false));
    }
  }).render('#paypal-button-container');
  //This function displays Smart Payment Buttons on your web page.
</script>

{% endblock scripts %}

templates/store/product_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}


<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'store:product-list' %}">Store</a>
                <span class="mx-2 mb-0"> > </span>
                <strong class="text-black">{{ product.title }}</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row mb-5">
        <div class="col-md-6">
            <img src="{{ product.image.url }}" alt="" class="img-fluid">
        </div>
        <div class="col-md-6">
            <h2 class="text-black">{{ product.title }}</h2>
            <h2><span class="badge badge-primary float-right">${{ product.get_price }}</span></h2>
            <p>{{ product.description }}</p>
            <p>Available stock: {{ product.stock }} units</p>
            {% if product.in_stock %}
            <form action="" method='post'>
                {% csrf_token %}
                {{ form|crispy }}
                <button type='submit' class='btn btn-sm btn-primary btn-block buy-now' >Add to Cart</button>
            </form>
            {% else %}
            <p>This item is out of stock</p>
            {% endif %}
        </div>     
        </div>
    </div>
</div>

{% endblock content %}

templates/store/product_list.html
 {% extends "base.html" %}
 {% load static %}

{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home'%}">Home</a>
                <span class="mx-2 mb-0"> > </span>
                <strong class="text-black">Store</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row mb-5">
        <div class="col-md-9 mb-4" data-aos='fade-up'>
            <div class="row mb-5">
            {% for product in object_list %}
                <div class="col-sm-6 col-lg-4 col-md-6 mb-4" data-aos="fade-up">
                    <figure class="block-4-image">
                        <a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" alt="" class="img-fluid"></a>
                    </figure>
                    <div class="block-4-text p-4">
                    <a href="{{ product.get_absolute_url }}">
                        <h4><span class="badge badge-primary float-right">${{ product.get_price }}</span></h4>
                        <h3>{{ product.title }}</h3>
                    </a>
                    <p class="mb-0">{{ product.description }}</p>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
        <div class="col-md-3 mb-4">
            <div class="border p-4 rounded mb-4">
                <h3 class="h6 text-uppercase text-black">Categories</h3>
                <ul>
                    {% for category in categories  %}
                    
                    <li class="mb-1">
                        <a href="?category={{ category.name }}" class="d-flex">
                            <span>{{ category.name }}</span>
                        </a>
                    </li>

                    {% endfor %}
                </ul>
            </div>
        </div>     
        </div>
    </div>
</div> 
{% endblock  %}

templates/store/thanks.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row mx-auto d-flex justify-content-center">
        <div class="col-md-12">
        <h2 class="text-center">Thank you for your order. We will get in touch with you soon!</h2>
        </div>
        <div class="row">
            <div class="col-md-12 border p-4 rounded" role="alert">
            <a href="{% url 'account_logout'%}"> Logout </a> or <a href="{% url 'store:product-list' %}"> Continue shopping </a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}